services:
  - type: web
    name: chat-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: chat-frontend
    env: node
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "npx serve -s build"
